services:
  - type: web
    name: fullstack-app
    env: docker
    plan: free
    repo: https://github.com/amusteikis/devops-fullstack-starter
    region: oregon
    dockerComposeFilePath: docker-compose.yml
    buildFilter:
      paths:
        - docker-compose.yml
        - frontend
        - backend
